version: "3"

services:
  mysql_db:
    image: mysql
    container_name: mysql_db
    networks:
      - nginx_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysqldatabase:/home

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - nginx_mysql
    ports:
      - 80:80

networks:
  nginx_mysql:
    driver: bridge

volumes:
  mysqldatabase:
    driver: local
